name: rsue_portfolio_api
description: Package for working with the portfolio API of the RSUE
version: 0.0.1

environment:
  sdk: '>=2.17.0-222.0.dev <3.0.0'

dependencies:
  html: ^0.15.0
  dio_cookie_manager: ^2.0.0
  dio: ^4.0.6

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
